all: download kmeans

download:
	wget http://ufal.mff.cuni.cz/~zabokrtsky/courses/npfl104/html/classification_data/pamap_easy.train.txt
	wget http://ufal.mff.cuni.cz/~zabokrtsky/courses/npfl104/html/classification_data/pamap_easy.test.txt

kmeans:
	python3 kmeans.py

